#!/usr/bin/env python

# DO NOT EDIT THIS FILE : Generated from scribe/notebooks/wakeword.ipynb

from  mangorest.mango import webapi
import colabexts.utils as colabexts_utils
import logging, os
import numpy as np
logger = logging.getLogger( "geoapp" )

# ------------------------------------------------------------------------------
def getModel(model = "llama-3" ):
    return None

@webapi("/cogs/lookup/")
def lookup(request=None, q="", **kwargs): 
    ret = q
    return ret

if __name__ == '__main__' and not colabexts_utils.inJupyter():
    lookup(None, None)
